### ISSUE TITLE
Should be Muddy Water

### ISSUE THREAD

**Issue by imp3tus** [123FLO321/RealDeviceMap#3]
https://github.com/123FLO321/RealDeviceMap/blob/f94347099b441ef1b26a14d99ea23df914be5452/resources/webroot/static/data/en.json#L1055

**Comment by 123FLO321** [comment]
Already fixed on latest master.
https://github.com/123FLO321/RealDeviceMap/commit/cc6b024b6e9b338ee38b077292f9432cc545ead6#diff-c82c1a39cf077f1c774dd424f8329063
